apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ay7v543ik-python 
  janus-idp.io/tekton: ay7v543ik-python
  backstage.io/kubernetes-id: ay7v543ik-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ay7v543ik-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml